
playsmf.exe: playsmf.obj midifile.obj
	cl /nologo /Fe..\bin\playsmf.exe .\playsmf.obj .\midifile.obj winmm.lib

midifile.obj:
	cl /nologo /I. /c .\midifile.c

playsmf.obj:
	cl /nologo /I. /c .\playsmf.c
